### ISSUE TITLE
Timeout error running rubrik_oracle_backup_mount 

### ISSUE THREAD

**Issue by lucky-lou** [pcrouleur/rubrik_oracle_tools#2]
Hello,
 
When we are running the rubrik_oracle_backup_mount the rubrik server takes several minutes to process it. As a result the script is timing out, but minutes later we see the live mount being prepared through the GUI.

Here is the command we are running:

rubrik_oracle_backup_mount -s cc2lxp190:gpro -m /oracle/gprj/rubrik_backup -h cc1lxd191

And here is the errror:

2021-05-03 11:40:25,925: Using most recent recovery point for mount.
2021-05-03 11:40:25,925: Starting the mount of the requested gpro backup pieces on cc1lxd191.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cc1rb01.ci.chandler.az.us', port=443): Read timed out. (read timeout=180)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rubrik_cdm/api.py", line 86, in _common_api
    api_request = requests.post(request_url, verify=False, headers=header, data=config, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cc1rb01.ci.chandler.az.us', port=443): Read timed out. (read timeout=180)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rubrik_oracle_backup_mount", line 11, in <module>
    load_entry_point('rubrikOracleTools', 'console_scripts', 'rubrik_oracle_backup_mount')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/oracle/nfs/xfer/migration/rubrik_oracle/rubrik_oracle_tools-master/rubrik_oracle_backup_mount.py", line 61, in cli
    live_mount_info = database.live_mount(host_id, time_ms, files_only=True, mount_path=mount_path)
  File "/oracle/nfs/xfer/migration/rubrik_oracle/rubrik_oracle_tools-master/rbs_oracle_common.py", line 256, in live_mount
    live_mount_info = self.rubrik.connection.post('internal', '/oracle/db/{}/mount'.format(self.oracle_id), payload, timeout=self.cdm_timeout)
  File "/usr/local/lib/python3.7/site-packages/rubrik_cdm/api.py", line 256, in post
    authentication=authentication)
  File "/usr/local/lib/python3.7/site-packages/rubrik_cdm/api.py", line 160, in _common_api
    "The Rubrik cluster did not respond to the API request in the allotted amount of time. To fix this issue, increase the timeout value.")
rubrik_cdm.exceptions.APICallException: The Rubrik cluster did not respond to the API request in the allotted amount of time. To fix this issue, increase the timeout value.

Is there a way to increase the timeout value the script will wait?

Thanks

**Comment by pcrouleur** [comment]
I added a parameter so the API timeout can be modified.  Now you can add --timeout 300 for example, and it should now use that higher value.  If you can pull the latest updates and let me know if that worked I would appreciate it. Thanks!

**Comment by lucky-lou** [comment]
Worked like a charm. Thank you!
